### PR TITLE
Adding --nohash flag

### PR DESCRIPTION
**Pull request by guillermosnipe**
--nohash flag allows you to remove the hash from generated filename.

### CODE REVIEW

**Comment by mixn** [comment]
Hey @guillermosnipe, thanks for chiming in and this PR. :)

I’d honestly like to keep the amount of `--flags` at a minimum. 🤔

Also, when/in what scenario was the hashed file name an issue for you? I feel like it is a useful feature and usually not a problem, since it keeps the alphabetical sorting in tact.

**Comment by guillermosnipe** [comment]
Hey @mixn nice to meet you! I need to generate several code images for appending them to some sort of certification questions exam. Having same filename but different extension will help me to easily identify images (eg: Question id: EXAMPLE001, image filename: EXAMPLE001.png)

As you can see in my example, having the hash included in the filename will cause some issues that I will need to fix with, for instance, a gulp task. By adding the flag (set to false by default), I just wanted to avoid altering the default tool behavior.

**Comment by mixn** [comment]
@guillermosnipe I’m in 🇨🇦 atm and will take a closer look at this when back. :) Not yet sure whether or not I’d want to add an extra `--flag` for something like this, since it seems like an edge case to me. I’ll leave it open for now though and see, maybe other people will chime in as well. 

Thanks for your work on this nevertheless, it’s appreciated! ❤️

**Comment by guillermosnipe** [comment]
@mixn you're welcome! You've developed a great and really helpful tool :) 👍 
Regarding whether it's an edge case or not, to me it doesn't look like that, because even when adding a hash to the name may have some advantages, it also has some cons: What about if you want to do cache busting with tools like [gulp-rev](https://github.com/sindresorhus/gulp-rev), you'll end up having filenames like this one:

`"js/unicorn.js": "js/unicorn-273c2c123f.js"`

with an additional hash you'll end up having a filename like this:

`"js/unicorn.js": "js/unicorn-a2393dkcdr-273c2c123f.js"`

Have a great day, we'll keep in touch :)

**Comment by mixn** [comment]
@guillermosnipe Thanks for your further work on this, I appreciate it. 🙂

> I’d honestly like to keep the amount of --flags at a minimum. 🤔

I really meant this when I said it though, since I just saw the 2nd additional flag, which is `--resize`.

I feel like this is beyond the scope of this project, as the CLI should ideally mirror the features of Carbon’s web app + have additional, useful, **common** CLI features like presets, a config file and interactive mode.

These features *seem* quite specific to your use case, as I have already stated. But I will leave this open to see if people will chime in. But don’t expect a merge any time soon, ok? 😊

Also, what is the point of cache-busting a basically cache-busted file? This CLI basically does that for you.

**Comment by mixn** [comment]
Also, if I’d have to pick `--nohash` or something like #30 , I’m leaning more towards the latter, since it does more things with the same amount of flags.

**Comment by guillermosnipe** [comment]
@mixn my bad, I've moved the resize capability to a different branch, because even when it would be a neat feature, it might be specific to my needs.
I'm not sure that you're doing cache busting, you're just recreating a different hash per run, while gulp-rev calculates the hash based on file contents.

I've reverted the master branch so it only contains the nohash flag.

#30 points out the same thing, would be very useful to get some control on how to name the file. I'm not very sure that I'm getting your point about it does more with less flags. 🤔 
What nohash does is just to remove the hash from the filename.

**Comment by mixn** [comment]
@guillermosnipe 

> @mixn my bad, I've moved the resize capability to a different branch, because even when it would be a neat feature, it might be specific to my needs.

No problem. :)

> I'm not sure that you're doing cache busting, you're just recreating a different hash per run, while gulp-rev calculates the hash based on file contents.

A different file name will lead to the file being cache-busted on websites, when replaced, is what I mean.

You’re right that it doesn’t compare files/contents and only regenerate a new hash then, but also, it shouldn’t — there are other tools for that. :)

There is also https://github.com/mixn/carbon-now-cli/issues/18, which initially lead to the hashing to just make sure people don’t unwillingly overwrite already existing images. That is very similar to the now open #30 — hence I will most likely implement it. :)

>  I'm not very sure that I'm getting your point about it does more with less flags. 🤔

`--no-hash` does exactly one thing with one flag: no generate a hash.
Something like `--output-name` or `--target` does two things with one flag: it doesn’t generate a flag **and** gives users the option to pick a file name.

Hence, it does more with one flag. Sorry, if that was unclear. :)

**Pull request closed without merging**
